#!/usr/bin/env bash

# A Bash script to transfer a file from a client to a server.
# Using the scp command, we are accepting the following arguments:
#   1. PATH_TO_FILE: The path to the file to be copied to the server.
#   2. IP: The IP address of the server to which the file will be transferred.
#   3. USERNAME: The username to connect to the server.
#   4. PATH_TO_SSH_KEY: The path to the SSH private key for authentication.

# Check if the correct number of arguments is provided
if [ $# -lt 4 ]; then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
    # If the correct number of arguments is provided, perform the file transfer
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~"
    # The scp command options used:
    # -o StrictHostKeyChecking=no: Disable strict host key checking to prevent interactive host key verification.
    # -i "$4": Specify the path to the SSH private key for authentication.
    # "$1": The path to the file to be transferred.
    # "$3@$2:~": The destination, which consists of the username and IP address of the server, followed by the home directory (~).

    # Check if the scp command was successful
    if [ $? -eq 0 ]; then
        echo "File transfer successful"
    else
        echo "File transfer failed"
        exit 1
    fi
fi
