#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file for distributing requests using a roundrobin algorithm
echo '
frontend Innocent.Sax
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 472848-web-01 52.73.73.32
        server 472848-web-02 34.207.212.203
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
