#!/usr/bin/env bash
# Script that prints the content of /etc/passwd file in a pretty format

IFS=':'
file='/etc/passwd'
while read -r USERNAME PASSWORD USER_ID GROUP_ID USER_INFO HOME_DIR SSHELL; do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIR and rides $SSHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_INFO"
done < "$file"

