#!/usr/bin/env bash
# substitute index 4, 9, and 17

k=1

while [ $k -le 20 ]
do
  echo "$k"
  case $k in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( k++ ))
done

